Replace layer5 logo with service mesh patterns logo in workflow
service-mesh-patterns/service-mesh-patterns pull request #104
Opened 2023-04-23 08:32 UTC by senali-d

**Description**

This PR fixes #102

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-23 08:36 UTC, l5io commented
🚀 Preview for commit 93a9cb2027fcb43cccd7f0525223205508a326be at: https://6444ede3954f5a012f17a9df--service-mesh-patterns.netlify.app

2023-05-08 18:46 UTC, thisiskaransgit commented
@senali-d, Better use these, for both color schemes
![Untitled (4)](https://user-images.githubusercontent.com/92504666/236899454-b900881a-dc83-40ea-a81f-67e3c54b1981.svg)
![Untitled (3)](https://user-images.githubusercontent.com/92504666/236899460-a0058fe6-c319-4763-b777-d06582e3e052.svg)

2023-05-08 18:47 UTC, thisiskaransgit requested changes
@senali-d, Better use these, for both color schemes
![Untitled (4)](https://user-images.githubusercontent.com/92504666/236899454-b900881a-dc83-40ea-a81f-67e3c54b1981.svg)
![Untitled (3)](https://user-images.githubusercontent.com/92504666/236899460-a0058fe6-c319-4763-b777-d06582e3e052.svg)

2023-05-11 14:14 UTC, HetviSoni commented
I would like to work on this issue.

2023-05-11 19:09 UTC, senali-d commented
@thisiskaransgit Requested change was done.

2023-05-17 08:50 UTC, thisiskaransgit commented
Hey @senali-d, the svgs were not passing the  quality check, @ritiksaxena124 has provided the recommended one, kindly update the images once more, and we are good to go.

![Patterns-dark](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/92504666/49a258c5-0896-42c9-abb2-34d49dcc0944)

![Patterns-light](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/92504666/de609bca-441b-41a9-86e4-b77606a917c5)

2023-05-19 09:21 UTC, HetviSoni commented on .github/config.yml
> +
As in meshery.io repo we have "Thanks for your contribution to the Layer5 **and Meshery**  community!"
so here we can have same here or maybe only Meshery
For reference: https://github.com/meshery/meshery.io/blob/master/.github/config.yml

2023-05-19 14:28 UTC, l5io commented
🚀 Preview for commit 12080b1e22c1231147579970ea4d796d91f4c0a2 at: https://646787949ea3ca22cd39aa02--service-mesh-patterns.netlify.app

2023-05-22 21:20 UTC, Chadha93 approved these changes

2023-05-22 21:21 UTC, merged