Adding Deployment Instructions for Patterns
service-mesh-patterns/service-mesh-patterns pull request #21
Opened 2021-12-11 08:51 UTC by Deepansharora27

**Description**

This PR fixes #8 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-12-11 09:01 UTC, Deepansharora27 commented
@warunicorn19 @Chadha93 Done with the Issue #8

2021-12-11 09:01 UTC, Deepansharora27 commented
Also tagging @leecalcote for the update

2021-12-12 06:51 UTC, Chadha93 requested changes
@Deepansharora27 By instructions we meant to just add the basic information about it in a gist, you don't have to copy all the information from the docs just referencing it with URLs will work.

@leecalcote @navendu-pottekkat would you please throw some light on this?

2021-12-12 14:44 UTC, Deepansharora27 commented
@Chadha93 Hi Gaurav, Kindly tell me then what part of information should I take into account for embedding into README file?

2021-12-13 06:19 UTC, navendu-pottekkat commented
Instructions on how to import pattern files that are stored in this repo through the UI and mesheryctl would be enough here.

You can point to the pattern files in this repo for examples.

After outlining the instructions briefly, you can point to the the Meshery docs.

2021-12-15 12:39 UTC, leecalcote commented
Thanks for jumping in here, @Deepansharora27 👍 

Will you remove the `.DS_Store` files and add an entry in the .gitignore file for these?

2021-12-20 08:11 UTC, Deepansharora27 commented
@leecalcote Roger that !!
Done with it

2021-12-20 08:11 UTC, Deepansharora27 commented
@navendu-pottekkat @Chadha93 I am done with the Changes,Can you please have a look ?

2021-12-23 08:00 UTC, Chadha93 approved these changes
@Deepansharora27 Cool Stuff :1st_place_medal:

2021-12-24 18:25 UTC, l5io approved these changes

2021-12-24 18:26 UTC, leecalcote commented on .gitignore
> +.DS_Store
Nice on, @Deepansharora27

2021-12-24 18:27 UTC, leecalcote approved these changes
Good work, @Deepansharora27

2021-12-24 18:27 UTC, merged