Added the aboutLayer5 Section from the authors Page
service-mesh-patterns/service-mesh-patterns pull request #81
Opened 2022-10-03 07:28 UTC by eeshaanSA

**Description**

This PR fixes #80 

**Notes for Reviewers**
Please suggest the changes that need to be made.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-10-03 07:38 UTC, eeshaanSA commented
// @legendarykamal @debo19 @leecalcote

2022-10-03 11:45 UTC, legendarykamal commented
@Nikhil-Ladha can you please start/run the workflows.

2022-10-03 11:51 UTC, l5io commented
🚀 Preview for commit db3f43ea0a2b8dd2d4a18cac9aa3b64e7ca0389e at: https://633acc99bf4c255f00a340b5--service-mesh-patterns.netlify.app

2022-10-03 11:52 UTC, Nikhil-Ladha commented
Hold this PR for sometime.

2022-10-19 06:04 UTC, eeshaanSA commented
@Nikhil-Ladha @leecalcote @debo19 can you review this, and give feedback?

2022-10-19 13:57 UTC, Nikhil-Ladha requested changes
Please rebase the code with the master and remove the duplicates from the PR i.e, the images and pages.
Also, you don't need to define the fonts again for a section it is already defined globally.

2022-10-20 10:50 UTC, eeshaanSA commented
@Nikhil-Ladha pl enable the workflows.

2022-10-20 12:16 UTC, l5io commented
🚀 Preview for commit e8d71d0a2c9f734c3850ee73dd0af6c9fd7489c3 at: https://63513bf6e53b071e0d85787e--service-mesh-patterns.netlify.app

2022-10-31 11:50 UTC, l5io commented
🚀 Preview for commit 3bc43c94cb5e9e74660df942a4a35a8ae7703cf1 at: https://635fb66e2c15d82307024a3f--service-mesh-patterns.netlify.app

2022-11-10 13:54 UTC, leecalcote commented
@UtkarshMishra12 please review.

2022-11-10 15:25 UTC, UtkarshMishra12 commented
@Lee On clicking the [About](https://636d0222fce5d9231d9fc660--service-mesh-patterns.netlify.app/) button it's redirecting to the page: layer5.io/company/about, but I think as per your suggestion there should be a dedicated page for this.

https://user-images.githubusercontent.com/67385503/201134333-dad5f85e-ccf8-4188-9a9f-c0bd322ee516.mp4

2022-11-12 20:55 UTC, UtkarshMishra12 commented
@leecalcote  On clicking the [About](https://636d0222fce5d9231d9fc660--service-mesh-patterns.netlify.app/) button it's redirecting to the page: layer5.io/company/about, but I think as per your suggestion there should be a dedicated page for this.
(i.e In short I'm not able to see the new About page )

https://user-images.githubusercontent.com/67385503/201134333-dad5f85e-ccf8-4188-9a9f-c0bd322ee516.mp4

2022-11-13 13:36 UTC, eeshaanSA commented
This makes sense according to me, @UtkarshMishra12. After this PR gets merged, there is going to be an about section just after the technical review, and not a different page.

2022-11-13 13:37 UTC, eeshaanSA commented
So, if we are to put the button there, it has to be directed to the Layer5 site.

2022-11-13 14:05 UTC, UtkarshMishra12 commented
@eeshaanSA Oh sorry😅, I thought you have added a new page for the about page on the navbar.

2022-11-13 14:25 UTC, UtkarshMishra12 reviewed
Please make the "about section" responsive as per the screen size of the device.
Also the button "Join the Layer5 Community"  is not working. (It should redirect to Slack)

https://user-images.githubusercontent.com/67385503/201526791-4f468e5d-03b9-4787-bb0e-e2f04082e3e8.mp4

2022-11-17 21:44 UTC, l5io commented
🚀 Preview for commit 11d0eb780cb5284feebb367d46a838f4ee92c4b5 at: https://6376ab1bb506891600af2a31--service-mesh-patterns.netlify.app

2022-11-18 07:31 UTC, l5io commented
🚀 Preview for commit 9644184b3884530cbc3761d1d5c9e891cc421e92 at: https://637734a11bb4ba0d9ceebb65--service-mesh-patterns.netlify.app

2022-11-18 08:35 UTC, UtkarshMishra12 reviewed
@eeshaanSA Now it's responsive as per the screen size, but I see when opening the site on mobile devices there is an irregular space in the para (see the video). Can you look at this?


https://user-images.githubusercontent.com/67385503/202657278-c19d5e28-fea7-4f35-8cf8-e840cd21f907.mp4

2022-11-19 05:18 UTC, eeshaanSA commented
Any idea what could be causing this? @UtkarshMishra12 
The irregular spaces?

2022-12-22 08:35 UTC, eeshaanSA commented
@Nikhil-Ladha can we have this merged?

2022-12-22 10:04 UTC, Nikhil-Ladha commented on site/src/sections/AboutLayer5/aboutl5io.style.js
> +  .outer-box {
```suggestion
  margin: 0.5rem auto 3rem;
  .outer-box {
```

2022-12-22 10:04 UTC, Nikhil-Ladha commented on site/src/sections/AboutLayer5/aboutl5io.style.js
> +    }
```suggestion
```

2022-12-22 10:04 UTC, Nikhil-Ladha commented on site/src/sections/AboutLayer5/aboutl5io.style.js
> +      margin: 4rem auto;
```suggestion
      margin: 2rem auto;
```

2022-12-22 10:04 UTC, Nikhil-Ladha commented on site/src/sections/AboutLayer5/aboutl5io.style.js
> +    line-height: 27px;
```suggestion
```

2022-12-22 10:05 UTC, Nikhil-Ladha approved these changes

2022-12-22 10:05 UTC, merged